### ISSUE TITLE
StandardOutputService class cannot be accessed

### ISSUE THREAD

**Issue by vaIerika** [GoodRequest/AppDebugMode-iOS#31]
When DebugMode was initially implemented StandardOutputService was public. Variable shouldRedirectLogsToAppDebugMode as well as redirectLogsToAppDebugMode() were accessed in the app, so you can change logs output source.

**Comment by andrej-jasso** [comment]
In the new version redirection is handled automatically without needing to set it up through the method call. Check AppDebugProvider class Setup function. Implicitly it should work if you just remove the API calls. But leave this issue there because also the shouldRedirectLogsToAppDebugMode variable is internal but should be public in case you want to turn it off for some reason.
